name: Lint all files on PR

'on': pull_request

jobs:
  lint_and_test:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run lint
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
